### PR TITLE
add opts argument to fromBuffer

### PR DESCRIPTION
**Pull request by ashaffer**

### CODE REVIEW

**Comment by bored-engineer** [comment]
Thanks!

**Comment by bored-engineer** [comment]
Pushed version `1.3.0-2` to npm with this fix.

**Comment by ashaffer** [comment]
Btw, did you every get this working with node-srp?  I tried it and first got this error, and then got an exponent out of range error after I fixed this, and wasn't able to figure that one out.

**Comment by bored-engineer** [comment]
I never got around to actually trying it, I'll probably do that in the next week or so and get back to you.

**Pull request merged**
